baseURL = "https://simontran7.github.io/"
languageCode = "en-us"
title = "Simon Tran"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block  = [["$$", "$$"]]
          inline = [["$", "$"]]
  [markup.highlight]
    style = "github"
    noClasses = false
